name: Build Release

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run release
